Repository BC-MOA/MOA-FE, pull requests merged in 2022-01, with the labels that each got.

#8 라우터 문법 오류 수정 및 라우터 구조 변경
  client/src/App.js
  client/src/index.js
  client/src/route/NavBar.js
  client/src/route/Routes.js
Labels: bug

#15 모으기 - 자유적금/비상금 작업 PR
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/assets/goal/army_character.svg
  client/src/assets/goal/cancel.svg
  client/src/assets/goal/check.svg
  client/src/assets/goal/clothes.svg
  client/src/assets/goal/date.svg
  client/src/assets/goal/date_active.svg
  client/src/assets/goal/electronic.svg
  client/src/assets/goal/etc.svg
  client/src/assets/goal/gift.svg
  client/src/assets/goal/ic_back.svg
  client/src/assets/goal/medical.svg
  client/src/assets/goal/travel.svg
  client/src/assets/goal/vacation.svg
  client/src/components/common/BackHeader.js
  client/src/components/gather/Category.js
  client/src/components/gather/CategoryEl.js
  client/src/components/gather/Complete.js
  client/src/components/gather/CustomBtn.js
  client/src/components/gather/CustomSelect.js
  client/src/components/gather/DatePick.js
  client/src/components/gather/Goal.js
  client/src/components/gather/MobileKeypad.js
  client/src/components/gather/SelectBox.js
  client/src/components/gather/StoreSvg.js
  client/src/components/gather/safebox/SafeBox.js
  client/src/components/gather/safebox/SliderInput.js
  client/src/components/gather/utils.js
  client/src/index.js
  client/src/route/NavBar.js
  client/src/route/Routes.js
  client/src/style/color.css
  client/src/style/common.js
  client/src/style/reset.css
Labels: enhancement

#22 하단 네비게이션 컴포넌트 PR
  client/src/assets/ic_nav_compete.svg
  client/src/assets/ic_nav_compete_active.svg
  client/src/assets/ic_nav_gather.svg
  client/src/assets/ic_nav_gather_active.svg
  client/src/assets/ic_nav_home.svg
  client/src/assets/ic_nav_home_active.svg
  client/src/assets/ic_nav_profile.svg
  client/src/assets/ic_nav_profile_active.svg
  client/src/components/common/NavBar.js
Labels: enhancement, Done

#24 열쇠 획득 페이지 PR
  client/src/assets/ic_close.svg
  client/src/assets/keyPopUp.png
  client/src/components/common/KeyPopUp.js
  client/src/route/Routes.js
Labels: enhancement, Done

#26 모으기 메인 페이지
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/common/Dropdown.js
  client/src/components/common/NavBar.js
  client/src/components/gather/AddBtn.js
  client/src/components/gather/Gather.js
  client/src/components/gather/StateGather.js
  client/src/components/gather/addGoal/CustomSelect.js
  client/src/components/gather/addGoal/Goal.js
Labels: enhancement, Done

#31 PR netlify 배포시 오류 코드 수정
  client/src/components/gather/addMilitarySavings/AddMilitarySavingsForm.js
  client/src/components/gather/addMilitarySavings/AddMilitarySavingsTerm.js
  client/src/components/gather/addMilitarySavings/MilitaryFormBox.js
  client/src/components/gather/addMilitarySavings/TermCheckBox.js
Labels: bug

#32 #30 fix : netlify 배포시 오류 코드 수정
  client/src/components/gather/addMilitarySavings/TermCheckBox.js
Labels: bug

#35 PR 리워드 상점 구매 박스 및 리워드 상품 카드 - 컴포넌트 제작
  client/src/assets/ic_key_small.svg
  client/src/assets/reward/reward_box_MOA박스.png
  client/src/assets/reward/reward_box_야금야금MOA박스.png
  client/src/assets/reward/reward_box_영끌MOA박스.png
  client/src/assets/reward/reward_box_왕창MOA박스.png
  client/src/assets/reward/reward_item_coffee.png
  client/src/components/reward/RewardBoxItem.js
  client/src/components/reward/RewardItemCard.js
Labels: enhancement, Done

#42 map 함수 warning 코드 수정
  client/src/components/gather/addMilitarySavings/AvailableSavingItemDetail.js
Labels: bug

#43 Troll compete
  client/package-lock.json
  client/package.json
  client/src/assets/compete/alarm-off.svg
  client/src/assets/compete/alarm-on.svg
  client/src/assets/compete/banner.png
  client/src/assets/compete/check.svg
  client/src/assets/compete/checked.svg
  client/src/assets/compete/game.png
  client/src/assets/compete/key-simple.svg
  client/src/assets/compete/key.svg
  client/src/assets/compete/moa.svg
  client/src/assets/compete/music.png
  client/src/assets/compete/panel.png
  client/src/assets/compete/soccer.png
  client/src/assets/compete/v1.png
  client/src/assets/compete/v2.png
  client/src/assets/compete/worldsoccer.png
  client/src/components/common/StyledLink.js
  client/src/components/compete/Common/Banner.js
  client/src/components/compete/Common/BannerSwiper.js
  client/src/components/compete/Common/BetCardButton.js
  client/src/components/compete/Common/Card.js
  client/src/components/compete/Common/DateChanger.js
  client/src/components/compete/Common/KeyBellHeader.js
  client/src/components/compete/Common/PercentBar.js
  client/src/components/compete/Common/PopUp.js
  client/src/components/compete/Common/SetCategory.js
  client/src/components/compete/Common/kFormatter.js
  client/src/components/compete/CompAllList.js
  client/src/components/compete/CompBody.js
  client/src/components/compete/CompDetail.js
  client/src/components/compete/CompHowTo.js
  client/src/components/compete/CompLists.js
  client/src/components/compete/CompMyList.js
  client/src/components/compete/Compete.js
  client/src/components/compete/context/CompContext.js
  client/src/route/Routes.js
  client/src/style/color.css
  client/src/style/reset.css
Labels: enhancement

#48 챌린지 리팩토링
  client/.vscode/settings.json
  client/src/components/common/Header.js
  client/src/components/compete/CompAllList.js
  client/src/components/compete/CompDetail.js
  client/src/components/compete/CompMyList.js
  client/src/components/compete/Compete.js
  client/src/components/compete/comp/BannerSwiper.js
  client/src/components/compete/comp/BetCardButton.js
  client/src/components/compete/comp/Card.js
  client/src/components/compete/comp/PercentBar.js
  client/src/components/compete/comp/PopUp.js
  client/src/components/compete/context/AllCompContext.js
  client/src/components/compete/context/CompContext.js
  client/src/components/compete/context/MyCompContext.js
  client/src/components/compete/context/data.js
Labels: bug, enhancement

#49 PR 리워드 페이지 일부 작업 완료
  client/src/assets/ic_key_big.svg
  client/src/assets/reward/barcode.svg
  client/src/assets/reward/ic_magnify.svg
  client/src/assets/reward/ic_to_more.svg
  client/src/components/common/ContentControlBtn.js
  client/src/components/gather/Gather.js
  client/src/components/gather/addMilitarySavings/AddMilitarySavings.js
  client/src/components/gather/addMilitarySavings/AvailableSavingItemDetail.js
  client/src/components/gather/addMilitarySavings/EditSavingTitle.js
  client/src/components/reward/MyBoxList.js
  client/src/components/reward/MyBoxListItem.js
  client/src/components/reward/MyProducItemDetail.js
  client/src/components/reward/MyProductList.js
  client/src/components/reward/MyProductListItem.js
  client/src/components/reward/MyReward.js
  client/src/components/reward/Reward.js
  client/src/components/reward/RewardBoxList.js
  client/src/components/reward/RewardUserInfo.js
  client/src/components/reward/example.png
  client/src/route/Routes.js
Labels: enhancement, Done

#51 PR 열쇠 클릭시 리워드 페이지로 이동 및 리워드 라우터 이동 플로우 수정
  client/src/components/common/Header.js
  client/src/components/reward/MyReward.js
Labels: bug, enhancement, Done

#54 PR 리워드 교환권 페이지 작업
  client/package-lock.json
  client/package.json
  client/src/components/reward/MyProducItemDetail.js
  client/src/style/color.css
Labels: enhancement

#55 PR 교환권 이미지 저장시 버튼 요소 깨짐 발생 이슈 해결
  client/src/components/reward/MyProducItemDetail.js
Labels: bug

#56 리워드 페이지 스타일 수정
  client/src/components/reward/MyProductListItem.js
  client/src/components/reward/RewardBoxItem.js
Labels: enhancement

#61 Troll compete
  client/src/assets/compete/Question_fill.svg
  client/src/assets/compete/popup.png
  client/src/components/common/StyledLink.js
  client/src/components/compete/CompAllList.js
  client/src/components/compete/CompDetail.js
  client/src/components/compete/comp/Card.js
  client/src/components/compete/comp/DetailPickup.js
  client/src/components/compete/comp/KeyExpect.js
  client/src/components/compete/comp/Picker.js
  client/src/components/compete/comp/PredictKey.js
  client/src/components/compete/comp/Timer.js
  client/src/components/compete/context/data.js
Labels: enhancement
