Repository BC-MOA/MOA-FE, pull requests merged in 2022-02, with the labels that each got.

#67 PR 홈 화면 일부 작업
  client/src/assets/about_moa.png
  client/src/assets/about_reward.png
  client/src/assets/army_character.png
  client/src/assets/reward/ic_refresh.svg
  client/src/assets/말풍선.png
  client/src/components/common/ScrollBox.js
  client/src/components/home/BubbleContent.js
  client/src/components/home/Home.js
  client/src/components/home/example.png
  client/src/components/profile/Profile.js
  client/src/components/reward/MyBoxOpen.js
Labels: enhancement

#68 PR 군적금 목표 설정 글자 바이트 제한 기능 추가
  client/src/components/gather/Gather.js
  client/src/components/gather/addMilitarySavings/EditSavingTitle.js
Labels: enhancement

#74 PR 군적금 신청 현황 관련 페이지 일부 작업
  client/src/assets/gather/ic_process_apply.svg
  client/src/assets/gather/ic_process_apply_green.svg
  client/src/assets/gather/ic_process_evaluation_green.svg
  client/src/assets/gather/ic_process_id_check_green.svg
  client/src/assets/gather/ic_process_maked_account_green.svg
  client/src/assets/gather/ic_shortcut.svg
  client/src/assets/ic_toggle_down.svg
  client/src/assets/ic_toggle_up.svg
  client/src/components/gather/MilitaryDetail.js
  client/src/components/gather/ProcessStateBox.js
  client/src/components/gather/addMilitarySavings/AddMilitarySavingSucess.js
  client/src/components/gather/addMilitarySavings/ProcessStateBox.js
  client/src/route/Routes.js
Labels: enhancement

#89 PR 리워드 페이지 추가 기능 작업
  client/src/assets/ic_key_big.svg
  client/src/assets/reward/character_head.svg
  client/src/assets/reward/ic_big_check.svg
  client/src/assets/reward/ic_big_error.svg
  client/src/assets/reward/notOpenBox.png
  client/src/assets/reward/opendBoxWithReward.png
  client/src/assets/reward/openedBox.png
  client/src/components/reward/BuyBox.js
  client/src/components/reward/MyBoxList.js
  client/src/components/reward/MyBoxOpen.js
  client/src/components/reward/MyProductList.js
  client/src/components/reward/MyReward.js
  client/src/components/reward/PopupRewardSelceted.js
  client/src/components/reward/Reward.js
  client/src/components/reward/RewardBoxItem.js
  client/src/components/reward/RewardBoxList.js
Labels: enhancement

#91 PR 리워드 배너 페이지 일부 작업
  client/src/assets/reward/aboutRewardBanner.png
  client/src/components/reward/AboutReward.js
  client/src/components/reward/Reward.js
  client/src/route/Routes.js
Labels: enhancement

#95 PR 스타일 수정 및 작은 열쇠 이미지 변경
  client/src/assets/ic_key_small.svg
  client/src/components/common/KeyPopUp.js
  client/src/components/gather/addMilitarySavings/AvailableSavingItemDetail.js
  client/src/components/home/Home.js
  client/src/components/reward/MyBoxList.js
  client/src/components/reward/MyBoxListItem.js
  client/src/components/reward/MyProducItemDetail.js
  client/src/components/reward/MyProductList.js
  client/src/components/reward/MyProductListItem.js
  client/src/components/reward/Reward.js
  client/src/components/reward/RewardBoxItem.js
  client/src/components/reward/RewardItemCard.js
Labels: enhancement

#96 PR 회원가입 이후 로딩 페이지 작업
  client/package-lock.json
  client/package.json
  client/src/assets/loading/loading_bank.png
  client/src/assets/loading/loading_character.png
  client/src/components/loading/Loading.js
  client/src/components/loading/LoadingStep1.js
  client/src/components/loading/LoadingStep2.js
  client/src/components/loading/LoadingStep3.js
  client/src/route/Routes.js
Labels: enhancement

#101 PR 리워드 페이지 - 로그인 정보 없을 시 로그인 페이지로 이동 로직 추가
  client/src/components/gather/addMilitarySavings/ApplyDataCard.js
  client/src/components/home/BubbleContent.js
  client/src/components/reward/MyBoxOpen.js
  client/src/components/reward/PopupRewardSelceted.js
  client/src/components/reward/Reward.js
  client/src/components/reward/RewardItemCard.js
  client/src/components/reward/RewardUserInfo.js
  client/src/components/signInUp/SignIn.js
  client/src/route/Routes.js
Labels: enhancement

#103 PR 리워드 이용방법 페이지 작업
  client/src/assets/reward/MOA_logo.svg
  client/src/assets/reward/aboutReward.png
  client/src/assets/reward/boxWithKey.png
  client/src/assets/reward/devider.svg
  client/src/assets/reward/ic_add.svg
  client/src/assets/reward/리워드주의사항.png
  client/src/components/reward/AboutReward.js
Labels: enhancement

#105 PR useContext 적용 및 은행 로고 이미지 이름 변경 및 파일 추가
  client/src/App.js
  client/src/assets/gather/ic_banklogo_DGB.svg
  client/src/assets/gather/ic_banklogo_IBK.svg
  client/src/assets/gather/ic_banklogo_KJB.svg
  client/src/assets/gather/ic_banklogo_국민.svg
  client/src/assets/gather/ic_banklogo_농협.svg
  client/src/assets/gather/ic_banklogo_신한.svg
  client/src/assets/gather/ic_banklogo_우리.svg
  client/src/assets/gather/ic_banklogo_우체국.svg
  client/src/assets/gather/ic_banklogo_제주.svg
  client/src/assets/gather/ic_banklogo_하나.svg
  client/src/components/common/Dropdown.js
  client/src/components/gather/TerminationCard.js
  client/src/components/gather/addMilitarySavings/ApplyDataCard.js
  client/src/components/gather/addMilitarySavings/AvailableSavingItem.js
  client/src/components/gather/addMilitarySavings/AvailableSavingList.js
  client/src/components/gather/addMilitarySavings/MilitaryAutoSavingForm.js
  client/src/components/gather/addMilitarySavings/MilitaryFormBox.js
  client/src/components/gather/addMilitarySavings/MilitaryFreeSavingForm.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavingSucess.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavings.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavingsForm.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavingsPassward.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavingsTerm.js
  client/src/components/gather/addMilitarySavings/views/AvailableSavingItemDetail.js
  client/src/route/Routes.js
  client/src/store/MiliSavingList.js
  client/src/store/Store.js
Labels: enhancement

#108 chore : 파일 구조 변경 및 주석 변경
  client/src/components/gather/addMilitarySavings/ApplyDataCard.js
  client/src/components/gather/addMilitarySavings/MilitaryAutoSavingForm.js
  client/src/components/gather/addMilitarySavings/MilitaryFormBox.js
  client/src/components/reward/RewardUserInfo.js
  client/src/components/reward/views/AboutReward.js
  client/src/components/reward/views/MyReward.js
  client/src/components/reward/views/Reward.js
  client/src/route/Routes.js
Labels: enhancement

#110 PR 배포서버 프록시 오류 해결
  client/netlify.toml
  client/src/components/home/Home.js
Labels: bug

#115 PR 리워드 페이지 더미 데이터 적용
  client/src/components/reward/BuyBox.js
  client/src/components/reward/MyBoxList.js
  client/src/components/reward/MyBoxListItem.js
  client/src/components/reward/MyProducItemDetail.js
  client/src/components/reward/MyProductList.js
  client/src/components/reward/MyProductListItem.js
  client/src/components/reward/PopupRewardSelceted.js
  client/src/components/reward/RewardBoxList.js
  client/src/components/reward/RewardItemCard.js
  client/src/components/reward/RewardUserInfo.js
  client/src/components/reward/views/MyBoxOpen.js
  client/src/components/reward/views/MyReward.js
  client/src/components/reward/views/Reward.js
  client/src/route/Routes.js
  client/src/store/BoxList.js
  client/src/store/Store.js
  client/src/store/UserInventory.js
Labels: enhancement

#117 PR 상자 오픈 클릭시 팝업 화면 추가
  client/src/assets/about_reward.png
  client/src/assets/keyPopUp.png
  client/src/assets/keyPopUp.svg
  client/src/assets/말풍선.png
  client/src/components/common/KeyPopUp.js
  client/src/components/reward/BuyBox.js
  client/src/components/reward/MyBoxList.js
  client/src/components/reward/MyBoxListItem.js
  client/src/components/reward/MyBoxOpenModal.js
Labels: enhancement

#118 fix : react hook import 경로 변경
  client/src/components/gather/addMilitarySavings/MilitaryAutoSavingForm.js
  client/src/components/gather/addMilitarySavings/views/AddMilitarySavingsPassward.js
  client/src/components/loading/Loading.js
Labels: bug

#119 feat : /loading에서 /interlock로 이동 코드 추가 및 이동 라우터 링크 url 수정
  client/src/components/loading/LoadingStep3.js
  client/src/components/signInUp/SignIn.js
Labels: enhancement

#120 #116 design : 팝업 버튼 스타일 수정
  client/src/components/reward/MyBoxOpenModal.js
Labels: enhancement

#128 fix : 교환권 저장 포맷 및 불필요한 코드 삭제
  client/src/components/home/BubbleContent.js
  client/src/components/reward/MyProducItemDetail.js
Labels: bug, enhancement

#130 프로필 관련
  client/src/assets/profile/병장.png
  client/src/assets/profile/상병.png
  client/src/assets/profile/이병.png
  client/src/assets/profile/일병.png
  client/src/components/interlock/data.js
  client/src/components/profile/comp/Account.js
  client/src/components/profile/comp/AccountCard.js
  client/src/components/profile/comp/DueProgressBar.js
  client/src/components/profile/comp/ProfileCard.js
  client/src/components/profile/function/dateFormat.js
  client/src/components/profile/function/userInfo.js
  client/src/components/profile/pages/Profile.js
  client/src/components/profile/pages/ProfileAccount.js
Labels: enhancement

#131 feat: 게시된 챌린지나 참여한가 없을 때 화면 추가
  client/src/assets/compete/empty.png
  client/src/components/compete/comp/Empty.js
  client/src/components/compete/function/FilterList.js
  client/src/components/compete/pages/CompAllList.js
  client/src/components/compete/pages/CompMyList.js
Labels: enhancement

#136 챌린지 추가 작업
  client/src/assets/compete/empty.png
  client/src/components/compete/comp/BannerSwiper.js
  client/src/components/compete/comp/Card/BetCompeteCard.js
  client/src/components/compete/comp/Empty.js
  client/src/components/compete/comp/PopUp.js
  client/src/components/compete/pages/CompAllList.js
  client/src/components/compete/pages/CompDetail.js
  client/src/components/compete/pages/CompMyList.js
Labels: enhancement

#191 오타 수정본 main에도 적용
  client/src/components/gather/addGoal/view/Goal.js
Labels: enhancement
